### **Causal Attention: hiding future words**

In [8]:
import torch
import torch.nn as nn

In [9]:
words = ['Your', 'journey', 'starts', 'with', 'one', 'step']

inputs = torch.tensor(
  [
   [0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55], # step     (x^6)
  ]
)

d_in = inputs.shape[-1] # embedding dimension
d_out = 2 # selected dimenstion of trainable weights
d_in, d_out

(3, 2)

In [10]:
class SelfAttention_v2(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values
        return context_vec

In [11]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)
sa_v2(inputs)

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)

In [ ]:
quaries = sa_v2.W_query(inputs)
keys = sa_v2.W_query(inputs)
attn_scores = quaries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
attn_weights

tensor([[0.1621, 0.1886, 0.1873, 0.1520, 0.1446, 0.1653],
        [0.1577, 0.1998, 0.1978, 0.1453, 0.1350, 0.1643],
        [0.1578, 0.1994, 0.1974, 0.1456, 0.1354, 0.1644],
        [0.1619, 0.1850, 0.1840, 0.1548, 0.1485, 0.1658],
        [0.1627, 0.1817, 0.1808, 0.1570, 0.1518, 0.1661],
        [0.1604, 0.1907, 0.1893, 0.1511, 0.1432, 0.1653]],
       grad_fn=<SoftmaxBackward0>)

lower and upper triangular matrix. so the `torch.tril` for lower triangular matrix and `torch.triu` for upper triangular matrix
![lower and upper triangular matrix](../images/L16_s3.png)


In [ ]:
# generate a mask for diagonal zeros for causal attention
context_length = attn_scores.shape[0]
# the tril is related to a concept in matrix called upper and lower triangular matrix. tril=lower triangular matrix which mean all values above the diagonal matrix are all zeros
mask_simple = torch.tril(torch.ones(context_length, context_length))
mask_simple

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [17]:
masked_simple = attn_weights * mask_simple
masked_simple

tensor([[0.1621, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1577, 0.1998, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1578, 0.1994, 0.1974, 0.0000, 0.0000, 0.0000],
        [0.1619, 0.1850, 0.1840, 0.1548, 0.0000, 0.0000],
        [0.1627, 0.1817, 0.1808, 0.1570, 0.1518, 0.0000],
        [0.1604, 0.1907, 0.1893, 0.1511, 0.1432, 0.1653]],
       grad_fn=<MulBackward0>)

In [25]:
# now the issue is that these weight cannot be our attention weights cause each row has to sum up to 1. so achieve this, we normalise each row
row_sums = masked_simple.sum(dim=1, keepdim=True)
masked_simple_norm = masked_simple / row_sums
masked_simple_norm

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4411, 0.5589, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2846, 0.3595, 0.3559, 0.0000, 0.0000, 0.0000],
        [0.2361, 0.2699, 0.2683, 0.2257, 0.0000, 0.0000],
        [0.1951, 0.2179, 0.2169, 0.1882, 0.1820, 0.0000],
        [0.1604, 0.1907, 0.1893, 0.1511, 0.1432, 0.1653]],
       grad_fn=<DivBackward0>)

The previous approach result in a data leakage and the reason is explained in the lecture 16 notes

In [26]:
attn_scores

tensor([[0.4775, 0.6915, 0.6818, 0.3861, 0.3155, 0.5048],
        [0.6915, 1.0263, 1.0121, 0.5753, 0.4714, 0.7497],
        [0.6818, 1.0121, 0.9981, 0.5674, 0.4649, 0.7393],
        [0.3861, 0.5753, 0.5674, 0.3227, 0.2645, 0.4203],
        [0.3155, 0.4714, 0.4649, 0.2645, 0.2169, 0.3444],
        [0.5048, 0.7497, 0.7393, 0.4203, 0.3444, 0.5476]],
       grad_fn=<MmBackward0>)

In [ ]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1) # start masking one above the main diagonal, so the diagonal itself stays 0.
masked = attn_scores.masked_fill(mask.bool(), -torch.inf) # whis line means, where value is true, replace with -inf(infinity) else replace with actual attention score. we also use infinity because, performing softmax on them, their value becomes 0.000 hence allowing the row value to sum up to 1
masked


tensor([[0.4775,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.6915, 1.0263,   -inf,   -inf,   -inf,   -inf],
        [0.6818, 1.0121, 0.9981,   -inf,   -inf,   -inf],
        [0.3861, 0.5753, 0.5674, 0.3227,   -inf,   -inf],
        [0.3155, 0.4714, 0.4649, 0.2645, 0.2169,   -inf],
        [0.5048, 0.7497, 0.7393, 0.4203, 0.3444, 0.5476]],
       grad_fn=<MaskedFillBackward0>)

now, all we need to do is apply the softmax function to these masked resuls, and we are done.

In [42]:
attn_weights = torch.softmax(masked / keys.shape[-1]**0.5, dim=-1)
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4411, 0.5589, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2846, 0.3595, 0.3559, 0.0000, 0.0000, 0.0000],
        [0.2361, 0.2699, 0.2683, 0.2257, 0.0000, 0.0000],
        [0.1951, 0.2179, 0.2169, 0.1882, 0.1820, 0.0000],
        [0.1604, 0.1907, 0.1893, 0.1511, 0.1432, 0.1653]],
       grad_fn=<SoftmaxBackward0>)

MASKING ADDITIONAL ATTENTION WEIGHTS WITH DROPOUT

In [45]:
torch.manual_seed(123)
dropout = torch.nn.Dropout(0.5)
example = torch.ones(6, 6)
print(example)
dropout(example)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


tensor([[2., 2., 2., 2., 2., 2.],
        [0., 2., 0., 0., 0., 0.],
        [0., 0., 2., 0., 2., 0.],
        [2., 2., 0., 0., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [0., 2., 0., 0., 0., 0.]])

In [46]:
# applying dropout to attention weights
torch.manual_seed(123)
dropout(attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.1178, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7119, 0.0000, 0.0000, 0.0000],
        [0.4721, 0.5397, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3902, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3814, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)

creating batches


In [47]:
batch = torch.stack((inputs, inputs), dim=0)
batch.shape

torch.Size([2, 6, 3])

In [48]:
class CausalAttention(nn.Module):

    def __init__(self, d_in, d_out, context_length,
                 dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose. basically so here we're swaping(transposing) the rows(context length) and the embedding dimension. eg: (2,6,3)->(2,3,6). this is done so that matrix multiplication can happen. the inner dimensions much be the same. eg 2x3x`6` @ `6`x3x2
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec

In [50]:
torch.manual_seed(123)
context_size = batch.shape[1]
ca = CausalAttention(d_in=d_in, d_out=d_out, context_length=context_size, dropout=0.0)
context_vecs = ca(batch)
context_vecs, context_vecs.shape

(tensor([[[-0.4519,  0.2216],
          [-0.5874,  0.0058],
          [-0.6300, -0.0632],
          [-0.5675, -0.0843],
          [-0.5526, -0.0981],
          [-0.5299, -0.1081]],
 
         [[-0.4519,  0.2216],
          [-0.5874,  0.0058],
          [-0.6300, -0.0632],
          [-0.5675, -0.0843],
          [-0.5526, -0.0981],
          [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>),
 torch.Size([2, 6, 2]))